In [3]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 10)
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

Run PCA with the corrected data

In [4]:
rna_df=pd.read_csv('./train_rna_corrected.tsv.txt', sep='\t')
pro_df=pd.read_csv('./train_pro_corrected.tsv.txt', sep='\t')
sum_df=pd.read_csv('./sum_tab_2.csv', sep=',', index_col='sample')

In [58]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

rna_df = rna_df.T
pro_df = pro_df.T


In [59]:
rna_df = rna_df.fillna(0)

In [60]:
pro_df = pro_df.fillna(0)

In [83]:
from sklearn.decomposition import PCA

In [62]:
X_pro = pro_df.values
X_rna = rna_df.values

In [63]:
pca = PCA(n_components=40)
pca.fit(X_rna)

PCA(copy=True, iterated_power='auto', n_components=40, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [64]:
pca.components_

array([[ 0.11308671,  0.10893383,  0.1088553 , ...,  0.1106744 ,
         0.1147969 ,  0.11230168],
       [-0.00407863,  0.10333338,  0.03140243, ...,  0.10373002,
        -0.0277355 ,  0.06591177],
       [ 0.11897635, -0.11013293,  0.01564081, ..., -0.06149707,
         0.0679699 ,  0.09267577],
       ..., 
       [-0.06932123,  0.06519819, -0.02750876, ...,  0.04620256,
        -0.07273821,  0.06788174],
       [ 0.13399105,  0.02281012, -0.04198756, ..., -0.01290452,
         0.02865626,  0.34762267],
       [-0.0740858 , -0.22359974,  0.0094874 , ...,  0.25847721,
         0.0185873 ,  0.03476323]])

In [65]:
df = pd.DataFrame(pca.components_)
df.to_csv("pca_rna_corrected.csv")

In [66]:
sum(pca.explained_variance_ratio_)

0.98643756814816375

In [67]:
pca = PCA(n_components=40)
pca.fit(X_pro)

PCA(copy=True, iterated_power='auto', n_components=40, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [68]:
pca.components_

array([[  1.15129923e-01,   1.22051242e-27,   1.15946265e-01, ...,
          1.09958575e-01,   1.13762898e-01,   1.14714775e-01],
       [  2.84705550e-02,   2.43935170e-21,  -6.23949006e-02, ...,
          1.81470269e-02,  -1.36455329e-01,  -1.06751412e-01],
       [ -3.47410182e-02,   9.21184008e-19,  -6.21377980e-02, ...,
          3.90356513e-02,   6.72965817e-02,  -1.18893764e-01],
       ..., 
       [  7.01988076e-02,  -1.01643072e-16,   4.92652622e-02, ...,
          8.04252832e-02,  -1.48406500e-01,   1.12038179e-01],
       [  4.17196960e-02,  -2.33178511e-17,   6.85542737e-02, ...,
         -5.91573165e-02,  -1.04481337e-01,  -5.10563083e-02],
       [  9.44063876e-02,  -8.19329727e-17,   4.65546167e-02, ...,
         -2.24871836e-01,  -1.57362846e-01,   1.01464882e-01]])

In [69]:
df = pd.DataFrame(pca.components_)
df.to_csv("pca_pro_corrected.csv")

In [70]:
sum(pca.explained_variance_ratio_)

0.95031065643177259

Run the pcs with corrected test data

In [71]:
rna_df=pd.read_csv('./test_rna_corrected.tsv.txt', sep='\t')
pro_df=pd.read_csv('./test_pro_corrected.tsv.txt', sep='\t')
sum_df=pd.read_csv('./sum_tab_2.csv', sep=',', index_col='sample')

In [76]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

rna_df = rna_df.T
pro_df = pro_df.T

In [78]:
pro_df

Testing_1  Testing_2  Testing_3  Testing_4  Testing_5  Testing_6  \
A1BG     3.446723   3.669580   3.398472   3.112875   3.535956   3.222556   
A2M      5.994520   6.371038   6.132440   5.645341   5.532811   5.754886   
AAAS     2.168001   2.410543        NaN   2.211822   0.987561   1.737837   
AACS          NaN   1.024838        NaN   1.099892   1.076615   1.001861   
AAGAB         NaN   0.991114   1.096724   1.056902        NaN        NaN   
...           ...        ...        ...        ...        ...        ...   
ZNF706   1.058798        NaN        NaN   1.780610   1.721321   1.017950   
ZPR1     1.848274   0.997150   1.120824   1.074043        NaN   1.584643   
ZW10     2.565798   2.265862   2.944166        NaN   1.795269   1.989170   
ZYX      3.597116   3.967766   3.779964   3.918465   3.535849   4.407917   
ZZEF1    1.636396   1.802938   1.756282        NaN        NaN   1.059954   

        Testing_7  Testing_8  Testing_9  Testing_10     ...      Testing_71  \
A1BG     4.011226   3.660633   2.459769    3.529445     ...        2.747886   
A2M      5.917435   6.056136   5.526915    5.652671     ...        6.164473   
AAAS     2.381688   2.193863   1.759665    2.310238     ...        2.842435   
AACS     1.924734   1.024838        NaN    1.878005     ...        2.481767   
AAGAB    1.010897   0.991114        NaN    1.010897     ...        1.181934   
...           ...        ...        ...         ...     ...             ...   
ZNF706   1.370977   1.005174        NaN    0.993088     ...        1.005174   
ZPR1     1.326519   2.422197        NaN    1.873740     ...        0.997150   
ZW10     2.293683   1.996383   1.181041    2.433754     ...        2.705029   
ZYX      3.839484   3.979165   4.041102    4.237667     ...        3.088232   
ZZEF1         NaN   2.463100   1.698926    2.255463     ...        2.481231   

        Testing_72  Testing_73  Testing_74  Testing_75  Testing_76  \
A1BG      3.107907    2.796258    3.975565    3.854046    3.840117   
A2M       6.404276    5.067085    6.497901    5.259377    6.172335   
AAAS      1.694889    1.520694    2.860077    2.233857    2.305192   
AACS           NaN    1.978784    1.024838         NaN    0.990946   
AAGAB     1.044511    1.010897    0.991114    1.066978         NaN   
...            ...         ...         ...         ...         ...   
ZNF706    1.744332    0.993088    1.005174    1.083073    1.005565   
ZPR1      1.059522    1.970412         NaN    1.085864    1.016313   
ZW10      1.817624    2.595059    1.477178    1.881899    1.850702   
ZYX       4.445406    4.644701    4.532813    3.969532    3.118259   
ZZEF1     1.020129    1.031065    2.458825    1.041180    1.678737   

        Testing_77  Testing_78  Testing_79  Testing_80  
A1BG      2.531494    2.642408    3.913182    4.141304  
A2M       5.496268    6.395966    5.963701    6.308505  
AAAS      1.470474    1.073909    1.102109    1.088823  
AACS      2.821773    1.428959         NaN         NaN  
AAGAB     1.911122         NaN    1.040694         NaN  
...            ...         ...         ...         ...  
ZNF706         NaN    1.508650    1.021728         NaN  
ZPR1      1.009531         NaN         NaN         NaN  
ZW10      2.016974    2.743954    1.593976    0.873647  
ZYX       4.220868    4.184490    4.173609    3.942143  
ZZEF1          NaN    2.181634         NaN    1.722888  

[4118 rows x 80 columns]

In [79]:
rna_df = rna_df.fillna(0)

In [80]:
pro_df = pro_df.fillna(0)

In [82]:
pro_df

Testing_1  Testing_2  Testing_3  Testing_4  Testing_5  Testing_6  \
A1BG     3.446723   3.669580   3.398472   3.112875   3.535956   3.222556   
A2M      5.994520   6.371038   6.132440   5.645341   5.532811   5.754886   
AAAS     2.168001   2.410543   0.000000   2.211822   0.987561   1.737837   
AACS     0.000000   1.024838   0.000000   1.099892   1.076615   1.001861   
AAGAB    0.000000   0.991114   1.096724   1.056902   0.000000   0.000000   
...           ...        ...        ...        ...        ...        ...   
ZNF706   1.058798   0.000000   0.000000   1.780610   1.721321   1.017950   
ZPR1     1.848274   0.997150   1.120824   1.074043   0.000000   1.584643   
ZW10     2.565798   2.265862   2.944166   0.000000   1.795269   1.989170   
ZYX      3.597116   3.967766   3.779964   3.918465   3.535849   4.407917   
ZZEF1    1.636396   1.802938   1.756282   0.000000   0.000000   1.059954   

        Testing_7  Testing_8  Testing_9  Testing_10     ...      Testing_71  \
A1BG     4.011226   3.660633   2.459769    3.529445     ...        2.747886   
A2M      5.917435   6.056136   5.526915    5.652671     ...        6.164473   
AAAS     2.381688   2.193863   1.759665    2.310238     ...        2.842435   
AACS     1.924734   1.024838   0.000000    1.878005     ...        2.481767   
AAGAB    1.010897   0.991114   0.000000    1.010897     ...        1.181934   
...           ...        ...        ...         ...     ...             ...   
ZNF706   1.370977   1.005174   0.000000    0.993088     ...        1.005174   
ZPR1     1.326519   2.422197   0.000000    1.873740     ...        0.997150   
ZW10     2.293683   1.996383   1.181041    2.433754     ...        2.705029   
ZYX      3.839484   3.979165   4.041102    4.237667     ...        3.088232   
ZZEF1    0.000000   2.463100   1.698926    2.255463     ...        2.481231   

        Testing_72  Testing_73  Testing_74  Testing_75  Testing_76  \
A1BG      3.107907    2.796258    3.975565    3.854046    3.840117   
A2M       6.404276    5.067085    6.497901    5.259377    6.172335   
AAAS      1.694889    1.520694    2.860077    2.233857    2.305192   
AACS      0.000000    1.978784    1.024838    0.000000    0.990946   
AAGAB     1.044511    1.010897    0.991114    1.066978    0.000000   
...            ...         ...         ...         ...         ...   
ZNF706    1.744332    0.993088    1.005174    1.083073    1.005565   
ZPR1      1.059522    1.970412    0.000000    1.085864    1.016313   
ZW10      1.817624    2.595059    1.477178    1.881899    1.850702   
ZYX       4.445406    4.644701    4.532813    3.969532    3.118259   
ZZEF1     1.020129    1.031065    2.458825    1.041180    1.678737   

        Testing_77  Testing_78  Testing_79  Testing_80  
A1BG      2.531494    2.642408    3.913182    4.141304  
A2M       5.496268    6.395966    5.963701    6.308505  
AAAS      1.470474    1.073909    1.102109    1.088823  
AACS      2.821773    1.428959    0.000000    0.000000  
AAGAB     1.911122    0.000000    1.040694    0.000000  
...            ...         ...         ...         ...  
ZNF706    0.000000    1.508650    1.021728    0.000000  
ZPR1      1.009531    0.000000    0.000000    0.000000  
ZW10      2.016974    2.743954    1.593976    0.873647  
ZYX       4.220868    4.184490    4.173609    3.942143  
ZZEF1     0.000000    2.181634    0.000000    1.722888  

[4118 rows x 80 columns]

In [84]:
X_pro = pro_df.values
X_rna = rna_df.values

In [86]:
pca = PCA(n_components=40)
pca.fit(X_rna)

PCA(copy=True, iterated_power='auto', n_components=40, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [87]:
pca.components_

array([[ 0.11480528,  0.10702349,  0.11425396, ...,  0.11096439,
         0.11022584,  0.10994328],
       [-0.01733079, -0.14643453,  0.20218028, ..., -0.06321224,
         0.0005539 ,  0.04318803],
       [-0.0857996 ,  0.00696597, -0.05369888, ...,  0.01901868,
         0.13208434,  0.22259583],
       ..., 
       [ 0.00844797, -0.02926784,  0.18154326, ...,  0.12208417,
         0.01573358,  0.11900813],
       [ 0.04546184, -0.11785823, -0.01431902, ..., -0.07572712,
         0.08938874, -0.12798559],
       [ 0.06170596, -0.08802367, -0.00746206, ..., -0.05221456,
        -0.09000101,  0.08411133]])

In [88]:
sum(pca.explained_variance_ratio_)

0.98700944993443873

In [89]:
df = pd.DataFrame(pca.components_)
df.to_csv("pca_testrna_corrected.csv")

In [90]:
pca = PCA(n_components=40)
pca.fit(X_pro)

PCA(copy=True, iterated_power='auto', n_components=40, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [91]:
pca.components_

array([[ 0.11611607,  0.10557598,  0.11632318, ...,  0.11189454,
         0.11635742,  0.11183904],
       [ 0.00068092,  0.04513877,  0.12133945, ..., -0.01418146,
         0.16038885,  0.18738847],
       [-0.0424725 , -0.09826213, -0.02746945, ..., -0.11920485,
        -0.10080131,  0.19739586],
       ..., 
       [ 0.14113428,  0.00238057, -0.01961897, ...,  0.06226982,
        -0.13888436,  0.07241683],
       [ 0.02645536,  0.03314593, -0.11369159, ..., -0.00289555,
         0.14969884, -0.05544583],
       [ 0.11562934, -0.00892164,  0.0578112 , ...,  0.09483136,
        -0.14662984, -0.16257219]])

In [92]:
sum(pca.explained_variance_ratio_)

0.94966367735695767

In [93]:
df = pd.DataFrame(pca.components_)
df.to_csv("pca_testpro_corrected.csv")